/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as PortDePlaisanceRouteImport } from './routes/port-de-plaisance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as RoomIdRouteImport } from './routes/room.$id'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as PortDePlaisanceTarifsRouteImport } from './routes/port-de-plaisance.tarifs'
import { Route as PortDePlaisanceReservationRouteImport } from './routes/port-de-plaisance.reservation'
import { Route as PortDePlaisancePlanRouteImport } from './routes/port-de-plaisance.plan'
import { Route as PortDePlaisanceFormalitesRouteImport } from './routes/port-de-plaisance.formalites'
import { Route as ClientReservationsRouteImport } from './routes/client.reservations'
import { Route as ClientRegisterRouteImport } from './routes/client.register'
import { Route as ClientProfileRouteImport } from './routes/client.profile'
import { Route as ClientMessagesRouteImport } from './routes/client.messages'
import { Route as ClientLoginRouteImport } from './routes/client.login'
import { Route as ClientDashboardRouteImport } from './routes/client.dashboard'
import { Route as BookIdRouteImport } from './routes/book.$id'
import { Route as AdminStatisticsRouteImport } from './routes/admin.statistics'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRoomsRouteImport } from './routes/admin.rooms'
import { Route as AdminReservationsRouteImport } from './routes/admin.reservations'
import { Route as AdminPortTarifsRouteImport } from './routes/admin.port-tarifs'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminDirectionRouteImport } from './routes/admin.direction'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminChannelsRouteImport } from './routes/admin.channels'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const PortDePlaisanceRoute = PortDePlaisanceRouteImport.update({
  id: '/port-de-plaisance',
  path: '/port-de-plaisance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const RoomIdRoute = RoomIdRouteImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortDePlaisanceTarifsRoute = PortDePlaisanceTarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => PortDePlaisanceRoute,
} as any)
const PortDePlaisanceReservationRoute =
  PortDePlaisanceReservationRouteImport.update({
    id: '/reservation',
    path: '/reservation',
    getParentRoute: () => PortDePlaisanceRoute,
  } as any)
const PortDePlaisancePlanRoute = PortDePlaisancePlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => PortDePlaisanceRoute,
} as any)
const PortDePlaisanceFormalitesRoute =
  PortDePlaisanceFormalitesRouteImport.update({
    id: '/formalites',
    path: '/formalites',
    getParentRoute: () => PortDePlaisanceRoute,
  } as any)
const ClientReservationsRoute = ClientReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => ClientRoute,
} as any)
const ClientRegisterRoute = ClientRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientRoute,
} as any)
const ClientMessagesRoute = ClientMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ClientRoute,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClientRoute,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatisticsRoute = AdminStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortTarifsRoute = AdminPortTarifsRouteImport.update({
  id: '/port-tarifs',
  path: '/port-tarifs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDirectionRoute = AdminDirectionRouteImport.update({
  id: '/direction',
  path: '/direction',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChannelsRoute = AdminChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/port-de-plaisance': typeof PortDePlaisanceRouteWithChildren
  '/presentation': typeof PresentationRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/channels': typeof AdminChannelsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/direction': typeof AdminDirectionRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/port-tarifs': typeof AdminPortTarifsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/book/$id': typeof BookIdRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/login': typeof ClientLoginRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/register': typeof ClientRegisterRoute
  '/client/reservations': typeof ClientReservationsRoute
  '/port-de-plaisance/formalites': typeof PortDePlaisanceFormalitesRoute
  '/port-de-plaisance/plan': typeof PortDePlaisancePlanRoute
  '/port-de-plaisance/reservation': typeof PortDePlaisanceReservationRoute
  '/port-de-plaisance/tarifs': typeof PortDePlaisanceTarifsRoute
  '/property/$id': typeof PropertyIdRoute
  '/room/$id': typeof RoomIdRoute
  '/client/': typeof ClientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/admin': typeof AdminRouteWithChildren
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/port-de-plaisance': typeof PortDePlaisanceRouteWithChildren
  '/presentation': typeof PresentationRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/channels': typeof AdminChannelsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/direction': typeof AdminDirectionRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/port-tarifs': typeof AdminPortTarifsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/book/$id': typeof BookIdRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/login': typeof ClientLoginRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/register': typeof ClientRegisterRoute
  '/client/reservations': typeof ClientReservationsRoute
  '/port-de-plaisance/formalites': typeof PortDePlaisanceFormalitesRoute
  '/port-de-plaisance/plan': typeof PortDePlaisancePlanRoute
  '/port-de-plaisance/reservation': typeof PortDePlaisanceReservationRoute
  '/port-de-plaisance/tarifs': typeof PortDePlaisanceTarifsRoute
  '/property/$id': typeof PropertyIdRoute
  '/room/$id': typeof RoomIdRoute
  '/client': typeof ClientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/port-de-plaisance': typeof PortDePlaisanceRouteWithChildren
  '/presentation': typeof PresentationRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/channels': typeof AdminChannelsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/direction': typeof AdminDirectionRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/port-tarifs': typeof AdminPortTarifsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/book/$id': typeof BookIdRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/login': typeof ClientLoginRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/register': typeof ClientRegisterRoute
  '/client/reservations': typeof ClientReservationsRoute
  '/port-de-plaisance/formalites': typeof PortDePlaisanceFormalitesRoute
  '/port-de-plaisance/plan': typeof PortDePlaisancePlanRoute
  '/port-de-plaisance/reservation': typeof PortDePlaisanceReservationRoute
  '/port-de-plaisance/tarifs': typeof PortDePlaisanceTarifsRoute
  '/property/$id': typeof PropertyIdRoute
  '/room/$id': typeof RoomIdRoute
  '/client/': typeof ClientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualites'
    | '/admin'
    | '/client'
    | '/confirmation'
    | '/contact'
    | '/login'
    | '/port-de-plaisance'
    | '/presentation'
    | '/register'
    | '/search'
    | '/admin/calendar'
    | '/admin/channels'
    | '/admin/clients'
    | '/admin/direction'
    | '/admin/invoices'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/port-tarifs'
    | '/admin/reservations'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/statistics'
    | '/book/$id'
    | '/client/dashboard'
    | '/client/login'
    | '/client/messages'
    | '/client/profile'
    | '/client/register'
    | '/client/reservations'
    | '/port-de-plaisance/formalites'
    | '/port-de-plaisance/plan'
    | '/port-de-plaisance/reservation'
    | '/port-de-plaisance/tarifs'
    | '/property/$id'
    | '/room/$id'
    | '/client/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualites'
    | '/admin'
    | '/confirmation'
    | '/contact'
    | '/login'
    | '/port-de-plaisance'
    | '/presentation'
    | '/register'
    | '/search'
    | '/admin/calendar'
    | '/admin/channels'
    | '/admin/clients'
    | '/admin/direction'
    | '/admin/invoices'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/port-tarifs'
    | '/admin/reservations'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/statistics'
    | '/book/$id'
    | '/client/dashboard'
    | '/client/login'
    | '/client/messages'
    | '/client/profile'
    | '/client/register'
    | '/client/reservations'
    | '/port-de-plaisance/formalites'
    | '/port-de-plaisance/plan'
    | '/port-de-plaisance/reservation'
    | '/port-de-plaisance/tarifs'
    | '/property/$id'
    | '/room/$id'
    | '/client'
  id:
    | '__root__'
    | '/'
    | '/actualites'
    | '/admin'
    | '/client'
    | '/confirmation'
    | '/contact'
    | '/login'
    | '/port-de-plaisance'
    | '/presentation'
    | '/register'
    | '/search'
    | '/admin/calendar'
    | '/admin/channels'
    | '/admin/clients'
    | '/admin/direction'
    | '/admin/invoices'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/port-tarifs'
    | '/admin/reservations'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/statistics'
    | '/book/$id'
    | '/client/dashboard'
    | '/client/login'
    | '/client/messages'
    | '/client/profile'
    | '/client/register'
    | '/client/reservations'
    | '/port-de-plaisance/formalites'
    | '/port-de-plaisance/plan'
    | '/port-de-plaisance/reservation'
    | '/port-de-plaisance/tarifs'
    | '/property/$id'
    | '/room/$id'
    | '/client/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualitesRoute: typeof ActualitesRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  ConfirmationRoute: typeof ConfirmationRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PortDePlaisanceRoute: typeof PortDePlaisanceRouteWithChildren
  PresentationRoute: typeof PresentationRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  BookIdRoute: typeof BookIdRoute
  PropertyIdRoute: typeof PropertyIdRoute
  RoomIdRoute: typeof RoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/port-de-plaisance': {
      id: '/port-de-plaisance'
      path: '/port-de-plaisance'
      fullPath: '/port-de-plaisance'
      preLoaderRoute: typeof PortDePlaisanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/room/$id': {
      id: '/room/$id'
      path: '/room/$id'
      fullPath: '/room/$id'
      preLoaderRoute: typeof RoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/port-de-plaisance/tarifs': {
      id: '/port-de-plaisance/tarifs'
      path: '/tarifs'
      fullPath: '/port-de-plaisance/tarifs'
      preLoaderRoute: typeof PortDePlaisanceTarifsRouteImport
      parentRoute: typeof PortDePlaisanceRoute
    }
    '/port-de-plaisance/reservation': {
      id: '/port-de-plaisance/reservation'
      path: '/reservation'
      fullPath: '/port-de-plaisance/reservation'
      preLoaderRoute: typeof PortDePlaisanceReservationRouteImport
      parentRoute: typeof PortDePlaisanceRoute
    }
    '/port-de-plaisance/plan': {
      id: '/port-de-plaisance/plan'
      path: '/plan'
      fullPath: '/port-de-plaisance/plan'
      preLoaderRoute: typeof PortDePlaisancePlanRouteImport
      parentRoute: typeof PortDePlaisanceRoute
    }
    '/port-de-plaisance/formalites': {
      id: '/port-de-plaisance/formalites'
      path: '/formalites'
      fullPath: '/port-de-plaisance/formalites'
      preLoaderRoute: typeof PortDePlaisanceFormalitesRouteImport
      parentRoute: typeof PortDePlaisanceRoute
    }
    '/client/reservations': {
      id: '/client/reservations'
      path: '/reservations'
      fullPath: '/client/reservations'
      preLoaderRoute: typeof ClientReservationsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/register': {
      id: '/client/register'
      path: '/register'
      fullPath: '/client/register'
      preLoaderRoute: typeof ClientRegisterRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/messages': {
      id: '/client/messages'
      path: '/messages'
      fullPath: '/client/messages'
      preLoaderRoute: typeof ClientMessagesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/login': {
      id: '/client/login'
      path: '/login'
      fullPath: '/client/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof ClientRoute
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statistics': {
      id: '/admin/statistics'
      path: '/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AdminStatisticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/port-tarifs': {
      id: '/admin/port-tarifs'
      path: '/port-tarifs'
      fullPath: '/admin/port-tarifs'
      preLoaderRoute: typeof AdminPortTarifsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/direction': {
      id: '/admin/direction'
      path: '/direction'
      fullPath: '/admin/direction'
      preLoaderRoute: typeof AdminDirectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/channels': {
      id: '/admin/channels'
      path: '/channels'
      fullPath: '/admin/channels'
      preLoaderRoute: typeof AdminChannelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminChannelsRoute: typeof AdminChannelsRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminDirectionRoute: typeof AdminDirectionRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPortTarifsRoute: typeof AdminPortTarifsRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStatisticsRoute: typeof AdminStatisticsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalendarRoute: AdminCalendarRoute,
  AdminChannelsRoute: AdminChannelsRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminDirectionRoute: AdminDirectionRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPortTarifsRoute: AdminPortTarifsRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStatisticsRoute: AdminStatisticsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientLoginRoute: typeof ClientLoginRoute
  ClientMessagesRoute: typeof ClientMessagesRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientRegisterRoute: typeof ClientRegisterRoute
  ClientReservationsRoute: typeof ClientReservationsRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientDashboardRoute: ClientDashboardRoute,
  ClientLoginRoute: ClientLoginRoute,
  ClientMessagesRoute: ClientMessagesRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientRegisterRoute: ClientRegisterRoute,
  ClientReservationsRoute: ClientReservationsRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface PortDePlaisanceRouteChildren {
  PortDePlaisanceFormalitesRoute: typeof PortDePlaisanceFormalitesRoute
  PortDePlaisancePlanRoute: typeof PortDePlaisancePlanRoute
  PortDePlaisanceReservationRoute: typeof PortDePlaisanceReservationRoute
  PortDePlaisanceTarifsRoute: typeof PortDePlaisanceTarifsRoute
}

const PortDePlaisanceRouteChildren: PortDePlaisanceRouteChildren = {
  PortDePlaisanceFormalitesRoute: PortDePlaisanceFormalitesRoute,
  PortDePlaisancePlanRoute: PortDePlaisancePlanRoute,
  PortDePlaisanceReservationRoute: PortDePlaisanceReservationRoute,
  PortDePlaisanceTarifsRoute: PortDePlaisanceTarifsRoute,
}

const PortDePlaisanceRouteWithChildren = PortDePlaisanceRoute._addFileChildren(
  PortDePlaisanceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualitesRoute: ActualitesRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  ConfirmationRoute: ConfirmationRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PortDePlaisanceRoute: PortDePlaisanceRouteWithChildren,
  PresentationRoute: PresentationRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  BookIdRoute: BookIdRoute,
  PropertyIdRoute: PropertyIdRoute,
  RoomIdRoute: RoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
